function expr = f(t,in2,param23,param24,param25,param26,param27,param28,param29,param30,param31,param32,param33,param34,param35,param36)
%F
%    EXPR = F(T,IN2,PARAM23,PARAM24,PARAM25,PARAM26,PARAM27,PARAM28,PARAM29,PARAM30,PARAM31,PARAM32,PARAM33,PARAM34,PARAM35,PARAM36)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    13-Feb-2017 09:28:21

t2 = cos(param36);
t3 = sin(param36);
t4 = param29+param30;

%Interpolating 
param34 = interp1(param33, param34,t);
param35 = interp1(param33, param35,t);
expr = [0.0;-param27.*param35.*t2.*t4-param29.*param30.*param32.*param35.*t2.*(param32-param31.*t3);param28.*param35.*t3.*t4+param29.*param30.*param31.*param32.*param35.*t2.^2];
