function expr = M(t,in2,param9,param10,param11,param12,param13,param14,param15,param16,param17,param18,param19,param20,param21,param22)
%M
%    EXPR = M(T,IN2,PARAM9,PARAM10,PARAM11,PARAM12,PARAM13,PARAM14,PARAM15,PARAM16,PARAM17,PARAM18,PARAM19,PARAM20,PARAM21,PARAM22)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    13-Feb-2017 09:28:20

%Interpolating
param20 = interp1(param19, param20,t);
param21 = interp1(param19, param21,t);

phi = in2(3,:);
theta = in2(2,:);
t2 = cos(theta);
t3 = param15+param16;
t4 = param20+phi;
t5 = sin(t4);
t6 = cos(t4);
t7 = param17.^2;
t8 = param18.^2;
t9 = sin(param22);
t10 = t7+t8-param17.*param18.*t9.*2.0;
t11 = cos(param20);
t12 = cos(phi);
t13 = sin(param20);
t14 = sin(phi);
t15 = cos(param22);
t16 = sin(theta);
t17 = t15.*t16;
t18 = t2.*t9.*t11.*t12;
t22 = t2.*t9.*t13.*t14;
t19 = t17+t18-t22;
t21 = param17.*t9;
t20 = param18-t21;
t23 = param18.*t19;
t24 = param17.*t2.*t13.*t14;
t25 = t23+t24-param17.*t2.*t11.*t12;
t26 = param17-param18.*t9;

expr = reshape([-param12.*t2.*t3.*t5-param15.*param16.*t2.*t5.*t10-param9.*t2.*t3.*t11.*t14-param11.*t2.*t3.*t12.*t13,param13.*t3.*t19+param15.*param16.*t20.*t25+param10.*t3.*t15.*t16+param11.*t2.*t3.*t9.*t11.*t12-param9.*t2.*t3.*t9.*t13.*t14,-param14.*t3.*(t9.*t16-t2.*t11.*t12.*t15+t2.*t13.*t14.*t15)-param10.*t3.*t9.*t16-param15.*param16.*param17.*t15.*t25+param11.*t2.*t3.*t11.*t12.*t15-param9.*t2.*t3.*t13.*t14.*t15,param12.*t3.*t6+param15.*param16.*t6.*t10+param9.*t3.*t11.*t12-param11.*t3.*t13.*t14,param13.*t3.*t5.*t9-param15.*param16.*t5.*t20.*t26+param9.*t3.*t9.*t12.*t13+param11.*t3.*t9.*t11.*t14,param14.*t3.*t5.*t15+param9.*t3.*t12.*t13.*t15+param11.*t3.*t11.*t14.*t15+param15.*param16.*param17.*t5.*t15.*t26,0.0,param10.*t3.*t15+param13.*t3.*t15+param15.*param16.*param18.*t15.*t20,-param10.*t3.*t9-param14.*t3.*t9-param15.*param16.*param17.*param18.*t15.^2],[3,3]);
